# Seed needs to be set at top of yaml, before objects with parameters are made
random_seed: 2023
__set_seed: !!python/object/apply:torch.manual_seed [!ref <random_seed>]

# shared variables
task: diagnostics-only
freeze_encoder: True
data_folder: ./data_og
dataset: Cambridge

# original audio and label file paths
wav_folder: !ref <data_folder>/<dataset>/wav/EN
audio_archive_path: !ref <wav_folder>/EN.zip
metadata_path: !ref <data_folder>/<dataset>/metadata/EN-metadata.csv

# data i/o paths
output_folder: !ref ./exps/<task>/brain-logs/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
rir_folder: !ref <data_folder>

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref ./exps/<task>/manifest/train.json
valid_annotation: !ref ./exps/<task>/manifest/valid.json
test_annotation: !ref ./exps/<task>/manifest/test.json
ratio: [0.7,0.1,0.2]
skip_prep: False

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    # metric: !name:speechbrain.utils.metric_stats.BinaryMetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

ckpt_interval_minutes: 15 # save checkpoint every N min


# Training Parameters
sample_rate: 16000
number_of_epochs: 20
batch_size: 16
lr_start: 0.1
lr_final: 0.001
n_classes: 1
emb_dim: 192 # dimensionality of the embeddings
dataloader_options:
    batch_size: !ref <batch_size>
    drop_last: True


# # Added noise and reverb come from OpenRIR dataset, automatically
# # downloaded and prepared with this Environmental Corruption class.
# env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
#     openrir_folder: !ref <rir_folder>
#     babble_prob: 0.0
#     reverb_prob: 1.0
#     noise_prob: 1.0
#     noise_snr_low: 0
#     noise_snr_high: 15

# # Adds speech change + time and frequency dropouts (time-domain implementation)
# # # A small speed change help to improve the performance of speaker-id as well.
# augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
#     sample_rate: !ref <sample_rate>
#     speeds: [95, 100, 105]


# model hyper-parameters
encoder_model: ECAPA

model: !new:model.SV_clf
    clf_input_shape: [null, null, !ref <emb_dim>]
    clf_activation: !name:torch.nn.LeakyReLU
    clf_lin_blocks: 1
    clf_lin_neurons: !ref <emb_dim>
    clf_out_neurons: !ref <n_classes>
    backbone_choice: !ref <encoder_model>
    pt_source: "speechbrain/spkrec-ecapa-voxceleb"
    mean_var_normalize_emb: False
    side_info: False
    freeze_extractor: True

# modules
modules:
    model: !ref <model>

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>


# This optimizer will be constructed by the Brain class after all parameters
# are moved to the correct device. Then it will be added to the checkpointer.
opt_class: !name:torch.optim.Adam
    lr: !ref <lr_start>

# This function manages learning rate annealing over the epochs.
# We here use the simple lr annealing method that linearly decreases
# the lr from the initial value to the final one.
lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr_start>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        counter: !ref <epoch_counter>
